Update CICD.yml

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -20,6 +20,31 @@ jobs:
         with:
           node-version: '22' # Node.js 22 버전으로 설정합니다.
 
+      - name: Determine Target Port
+        id: determine-port
+        run: |
+          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.STMARY_IP }}/env")
+          echo $STATUS
+          if [ $STATUS = 200 ]; then
+            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.STMARY_IP }}/env")
+          else
+            CURRENT_UPSTREAM=green
+          fi
+          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+          if [ $CURRENT_UPSTREAM = blue ]; then
+            echo "TARGET_PORT=8081" >> $GITHUB_ENV
+            echo "TARGET_ENV=green" >> $GITHUB_ENV
+          elif [ $CURRENT_UPSTREAM = green ]; then
+            echo "TARGET_PORT=8080" >> $GITHUB_ENV
+            echo "TARGET_ENV=blue" >> $GITHUB_ENV
+          else
+            echo "error"
+            exit 1
+          fi
+
+      - name: Update .env file for React app
+        run: echo "VITE_API_URL='http://3.34.15.114:${{ env.TARGET_PORT }}'" > FrontEnd/.env
+
       - name: Install dependencies
         working-directory: FrontEnd
         run: npm ci
@@ -46,8 +71,8 @@ jobs:
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Build Docker
-        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/stmary .
-        
+        run: docker build --platform linux/amd64 --build-arg PROFILES=${{ env.TARGET_ENV }} --build-arg ENV=${{ env.TARGET_ENV }} -t ${{ secrets.DOCKERHUB_USERNAME }}/stmary .
+
       - name: Push Docker
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/stmary:latest
         
@@ -116,3 +141,121 @@ jobs:
           script: |
             sudo docker stop ${{env.CURRENT_UPSTREAM}}
             sudo docker rm ${{env.CURRENT_UPSTREAM}}
+# name: CICD
+
+# on:
+#   push:
+#     branches: [ "main" ]
+#   pull_request:
+#     branches: [ "main" ]
+
+# permissions:
+#   contents: read
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@v4
+
+#       - name: Set up Node.js
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: '22' # Node.js 22 버전으로 설정합니다.
+
+#       - name: Install dependencies
+#         working-directory: FrontEnd
+#         run: npm ci
+
+#       - name: Build React app
+#         working-directory: FrontEnd
+#         run: npm run build
+        
+#       - name: Set up JDK 17
+#         uses: actions/setup-java@v4
+#         with:
+#           java-version: '17'
+#           distribution: 'temurin'
+
+#       - name: Build with Gradle
+#         run: |
+#           chmod +x ./gradlew
+#           ./gradlew bootJar
+
+#       - name: Login to DockerHub
+#         uses: docker/login-action@v1
+#         with:
+#           username: ${{ secrets.DOCKERHUB_USERNAME }}
+#           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+#       - name: Build Docker
+#         run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/stmary .
+        
+#       - name: Push Docker
+#         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/stmary:latest
+        
+#   deploy:
+#     needs: build
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Set target IP
+#         run: |
+#           STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.STMARY_IP }}/env")
+#           echo $STATUS
+#           if [ $STATUS = 200 ]; then
+#             CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.STMARY_IP }}/env")
+#           else
+#             CURRENT_UPSTREAM=green
+#           fi
+#           echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+#           if [ $CURRENT_UPSTREAM = blue ]; then
+#             echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+#             echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+#             echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+#           elif [ $CURRENT_UPSTREAM = green ]; then
+#             echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+#             echo "STOPPED_PORT=8080" >> $GITHUB_ENV
+#             echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+#           else
+#             echo "error"
+#             exit 1
+#           fi
+          
+#       - name: Docker compose
+#         uses: appleboy/ssh-action@master
+#         with:
+#           username: ubuntu
+#           host: ${{ secrets.STMARY_IP }}
+#           key: ${{ secrets.EC2_SSH_KEY }}
+#           script_stop: true
+#           script: |
+#             sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/stmary:latest
+#             sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
+      
+#       - name: Check deploy server URL
+#         uses: jtalk/url-health-check-action@v3
+#         with:
+#           url: http://${{ secrets.STMARY_IP }}:${{env.STOPPED_PORT}}/env
+#           max-attempts: 10
+#           retry-delay: 10s
+
+#       - name: Change nginx upstream
+#         uses: appleboy/ssh-action@master
+#         with:
+#           username: ubuntu
+#           host: ${{ secrets.STMARY_IP }}
+#           key: ${{ secrets.EC2_SSH_KEY }}
+#           script_stop: true
+#           script: |
+#             sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 
+
+#       - name: Stop current server
+#         uses: appleboy/ssh-action@master
+#         with:
+#           username: ubuntu
+#           host: ${{ secrets.STMARY_IP }}
+#           key: ${{ secrets.EC2_SSH_KEY }}
+#           script_stop: true
+#           script: |
+#             sudo docker stop ${{env.CURRENT_UPSTREAM}}
+#             sudo docker rm ${{env.CURRENT_UPSTREAM}}
